### ISSUE TITLE
window does not get painted when starlink is powered off

### ISSUE THREAD

**Issue by joeyh** [bmillham/starlink-graph#4] opened 2022-08-02 14:55 UTC
I power my starlink terminal off overnight to save power, and I noticed that, when it's powered off, starlink-graph's window does not get painted, at all.

When it's in this state, this gets output on the console:

   Not connected: UNKNOWN@2022-08-02 10:48:47.159192-04:00
   No history returned
   Not connected: UNKNOWN@2022-08-02 10:48:53.393420-04:00
   No history returned

**Comment by bmillham** [comment] 2022-08-03 00:11
I believe that this is related to the other issue that I just pushed a fix for. Please let me know if it was fixed by that push.

**Comment by bmillham** [comment] 2022-08-03 08:51
I just re-read this.
The problem is that if the dish is off that you get no graph, right?
I'm not sure how I should handle this.
Maybe a message like 'Unable to contact dish'?
Thoughts?

**Comment by bmillham** [comment] 2022-08-06 09:44
Is this fixed? If I get no feedback I'll assume that it is.

**Comment by bmillham** [comment] 2022-08-10 05:34
Since you haven't responded I'm considering that this is fixed. If not, please open a new issue.

**Closed as completed by bmillham** 2022-08-10 05:34 UTC
